name: Build and Push Docker Image - Service Years

on:
  push:
    branches:
      - main
    directories:
      - 'services/service-years/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image - years
        working-directory: services/service-years/
        run: |
          docker build -t docker.redby.fr/gallery/service-years:latest .

      - name: Build Docker image - albums
        working-directory: services/service-albums/
        run: |
          docker build -t docker.redby.fr/gallery/service-albums:latest .

      - name: Push Docker image - years
        working-directory: services/service-years/
        run: |
          docker push docker.redby.fr/gallery/service-years:latest

      - name: Push Docker image - albums
        working-directory: services/service-albums/
        run: |
          docker push docker.redby.fr/gallery/service-albums:latest