name: Build and Push Docker Image - Service Years

on:
  push:
    branches:
      - main

jobs:
  years:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image - years
        working-directory: services/years/
        run: |
          docker buildx build --platform linux/arm/v7 -t docker.redby.fr/gallery/service-years:latest --push .

  albums:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image - albums
        working-directory: services/albums/
        run: |
          docker buildx build --platform linux/arm/v7 -t docker.redby.fr/gallery/service-albums:latest --push .

  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image - frontend
        working-directory: frontend/
        run: |
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t docker.redby.fr/gallery/frontend:latest --push .
